---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/users":
    post:
      summary: Creates a user and returns a JWT token
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  sym_key_salt:
                    type: string
                required:
                - token
                - sym_key_salt
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/protected_route":
    get:
      summary: Returns the authenticated user
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: 'JWT token in the format: Bearer <token>'
        schema:
          type: string
      responses:
        '200':
          description: user info returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                required:
                - id
                - username
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
  "/login":
    post:
      summary: Logs in a user and returns a JWT token
      tags:
      - Authentication
      parameters: []
      responses:
        '202':
          description: successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  sym_key_salt:
                    type: string
                required:
                - token
                - sym_key_salt
        '401':
          description: unauthorized (invalid credentials or unknown user)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/secrets":
    get:
      summary: List secrets of the authenticated user
      tags:
      - Secrets
      security:
      - bearer_auth: []
      responses:
        '200':
          description: secrets listed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    value:
                      type: string
                    user_id:
                      type: integer
                  required:
                  - id
                  - value
                  - user_id
    post:
      summary: Create a secret
      tags:
      - Secrets
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: secret created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  value:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - value
                - user_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                user_id:
                  type: integer
              required:
              - value
              - user_id
  "/secrets/{id}":
    parameters:
    - name: id
      in: path
      description: Secret ID
      required: true
      schema:
        type: integer
    get:
      summary: Get a specific secret
      tags:
      - Secrets
      security:
      - bearer_auth: []
      responses:
        '200':
          description: secret found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  value:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - value
                - user_id
        '403':
          description: not your secret
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
    patch:
      summary: Update a secret
      tags:
      - Secrets
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: secret updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  value:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - value
                - user_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
    delete:
      summary: Delete a secret
      tags:
      - Secrets
      security:
      - bearer_auth: []
      responses:
        '204':
          description: secret deleted
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
